all:
  hosts:
    web2018-prod-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0041p-webcdn
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
      inventory_environment: prod
  vars:
    hostname: 'web2018.epfl.ch'
    tag: 8.0.1
