all:
  hosts:
    web2018-prod-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0041p-webcdn
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
      inventory_environment: prod
  vars:
    hostnames:
      - { name: 'web2018.epfl.ch', availability: 'public-cf' }
      - { name: 'prod-web2018-origin.epfl.ch', availability: 'private' }
    tag: dev.20250508152549.034380d.348
