all:
  hosts:
    web2018-staging-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0041t-webcdn
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
      inventory_environment: staging
  vars:
    hostname: 'staging-web2018.epfl.ch'
    tag: 8.0.1
