- name: Web2018 - Robot pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: '{{ app_name }}-pull-secret'
        namespace: '{{ openshift_namespace }}'
      data:
        .dockerconfigjson: '{{ secrets.quay.robot.dockerconfig }}'
