name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Hadolint
        run: make hadolint

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: |
          yarn install
          yarn test
          npm version --commit-hooks false --git-tag-version false patch
          yarn release
